# Generated by Django 5.0.6 on 2024-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Crochets', 'Crochets'), ('Crochet Bundles', 'Crochet Bundles'), ('Donmac', 'Donmac')], default='crochets', max_length=25),
        ),
    ]
